title: 電研ブログ
author: 大阪産業大学文化会 電子計算研究部
theme: minima
baseurl: "/blog"
markdown: kramdown
commonmark:
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: 
    - strikethrough
    - autolink
    - table
    - tagfilter
    - jekyll-paginate
kramdown:
  input: GFM
  autolink: true
  tables: true
  
paginate: 10
paginate_path: "/page:num/"
